Module 1: Hello World Project
seyioyemade/hello-world pull request #1
Opened 2023-02-14 20:42 UTC by seyioyemade

## Module 1: Hello World Project

In this project I:

- Created a branch according to the [GitHub flow].
- Added a .gitignore file.
- Added node_modules to gitignore file.
- Set up a linter for HTML and CSS.
- Added descriptive README file.
- Added a .html file that includes a header with the text "Hello Microverse!". 
- Added a .css file that includes one class with styles for the header.
- Added a test.md file to gitignore.

2023-02-14 21:08 UTC, osamaashraf6 requested changes
Hi @seyioyemade 😊, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![you-are-near](https://media.giphy.com/media/SSR17K6yZWvGCYrfUh/giphy.gif)


## Highlights 💯🎉

- [x] Good descriptive pull request
- [x] Good following GitHub flow 


## Required Changes ♻️

- [ ]  Please consider using best practices when you write commit messages, they should be capitalized sentences in the imperative form, for example: "Add linters configuration" instead of "add linters configuration" ... etc 👍
- [ ] You did a great job 😃 at adding the configuration for the linter, but as you see here there is an error linter at the eslint, so please 😊 try to fix that to remove the error of the linter I suggest you use the ```  npx eslint . --fix ``` command in the terminal to fix the error of linter at js 💯


- Check the comments under the review._

## Optional suggestions
 N/A
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-14 21:08 UTC, osamaashraf6 commented on README.md
> +HTML and CSS
- [ ] Kindly 😊 use [the Microverse Readme template](https://github.com/microverseinc/readme-template) and make sure all the main sections present in yours and placeholders are replaced with your project and personal data. The only optional section is a FAQ. Please remove the template logo on the top, if you have one, you can replace it. This is crucial to have a professional and instructive repository. 👌

2023-02-15 09:22 UTC, Olamarx requested changes
Hi @seyioyemade, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.
<img src="https://media1.giphy.com/media/t8YPf3ACKeouLzEIvr/giphy.gif"/>

 ## Highlights
- commit messages ✔️ 
- Linters passed ✔️

 ## Required Changes ♻️
_Check the comments under the review._
- [ ] I see your readme is yet to use the professionally provided template by Microverse, as suggested by the previous reviewer, I would implore you to use it and adapt it to your own project by filling it out according to your project so that you or any other visitor can easily grasp what the repo entails at a glance. You can find the template [here](https://github.com/microverseinc/readme-template)

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-15 10:08 UTC, seyioyemade commented
Hi Olaoluwa,

Thank you for reviewing my project.

I'm left with just one request review and I made sure I used the Microverse
readme template.

I don't know what to do from here. Kindly elaborate on your review.

Please help me.

Seyi Oyemade

On Wed, 15 Feb 2023 at 10:22, Olaoluwa Owoeye ***@***.***>
wrote:

> ***@***.**** requested changes on this pull request.
>
> Hi @seyioyemade <https://github.com/seyioyemade>,
>
> Great work on making the changes requested by a previous reviewer 👏
> You've done well implementing some of the requested changes, but there are
> still some which aren't addressed yet.
>
> <https://camo.githubusercontent.com/957cdd5c6c73009f305aa460cba68fe9b38c4cf1eead69c6006a391516168166/68747470733a2f2f6d65646961312e67697068792e636f6d2f6d656469612f74385950663341434b656f754c7a454976722f67697068792e676966>
> Highlights
>
>    - commit messages ✔️
>    - Linters passed ✔️
>
> Required Changes ♻️
>
> *Check the comments under the review.*
>
>    - I see your readme is yet to use the professionally provided template
>    by Microverse, as suggested by the previous reviewer, I would implore you
>    to use it and adapt it to your own project by filling it out according to
>    your project so that you or any other visitor can easily grasp what the
>    repo entails at a glance. You can find the template here
>    <https://github.com/microverseinc/readme-template>
>
> Optional suggestions
>
> *Every comment with the [OPTIONAL] prefix won't stop the approval of this
> PR. However, I strongly recommend you to take them into account as they can
> make your code better. Some of them were simply missed by the previous
> reviewer and addressing them will really improve your application.*
>
> Cheers and Happy coding!👏👏👏
>
> Feel free to leave any questions or comments in the PR thread if something
> is not 100% clear.
> Please, remember to tag me in your question so I can receive the
> notification.
>
> *Please, do not open a new Pull Request for re-reviews. You should use the
> same Pull Request submitted for the first review, either valid or invalid
> unless it is requested otherwise.*
> ------------------------------
>
> *As described in the Code reviews limits policy
> <https://microverse.zendesk.com/hc/en-us/articles/1500004088561> you have a
> limited number of reviews per project (check the exact number in your
> Dashboard). If you think that the code review was not fair, you can request
> a second opinion using this form <https://airtable.com/shrQAqnBwek5a0O0s>.*
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/seyioyemade/hello-world/pull/1#pullrequestreview-1299106718>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/A3IEW755PUHKUJFI2SO5OE3WXSN5DANCNFSM6AAAAAAU4A5FQY>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2023-02-15 10:08 UTC, seyioyemade commented
@Olamarx

Thank you for reviewing my project.

I'm left with just one request review and I made sure I used the Microverse readme template.

I don't know what to do from here. Kindly elaborate on your review.


Please help me.

Seyi Oyemade

2023-02-15 10:10 UTC, Olamarx commented
I think you removed majority of the content then, kindly try not to remove, just replace with your own content. Do you understand?

2023-02-15 10:34 UTC, seyioyemade commented
Okay. 
Thank you.

2023-02-15 11:34 UTC, seyioyemade commented
@Olamarx 

Thank you for your time earlier.

I have redone and added the Microverse Readme template properly.

Kindly help check the readme file in my last commit to ensure I did it correctly this time. I have one review chance left in my dashboard  🙏

2023-02-15 11:59 UTC, seyioyemade commented
Thank you for your time earlier.

I have redone and added the Microverse Readme template properly.

Kindly help check the readme file in my last commit to ensure I did it
correctly this time. I have one review chance left on my dashboard 🙏


Please.

On Wed, 15 Feb 2023 at 11:10, Olaoluwa Owoeye ***@***.***>
wrote:

> I think you removed majority of the content then, kindly try not to
> remove, just replace with your own content. Do you understand?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/seyioyemade/hello-world/pull/1#issuecomment-1431067140>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/A3IEW77JIYRCV4FPREKG4QTWXSTTDANCNFSM6AAAAAAU4A5FQY>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2023-02-15 14:17 UTC, souad988 approved these changes
Hi @seyioyemade , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
✔Good PR description 
✔Good commit messages.
 ✔Clear and good communication with reviewers in the comments.

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-15 14:17 UTC, souad988 commented on README.md
> +
[ OPTIONAL ]
well done @seyioyemade, you implemented all this project requirements and applied all changes required by previous reviewers 💪, one small thing to mention is that the content of this section should move to setup and here all user have to do is run ' npm install '.

2023-02-15 14:23 UTC, seyioyemade commented
Thanks for the feedback! 😊

On Wed, 15 Feb 2023 at 15:17, Souad El Mansouri ***@***.***>
wrote:

> ***@***.**** approved this pull request.
>
> Hi @seyioyemade <https://github.com/seyioyemade> ,
>
> Your project is complete! There is nothing else to say other than... it's
> time to merge it [image: :shipit:]
> Congratulations! 🎉
> Highlights
>
> ✔Good PR description
> ✔Good commit messages.
> ✔Clear and good communication with reviewers in the comments.
> Optional suggestions
>
> *Every comment with the [OPTIONAL] prefix won't stop the approval of this
> PR. However, I strongly recommend you to take them into account as they can
> make your code better. Some of them were simply missed by the previous
> reviewer and addressing them will really improve your application.*
>
> Cheers and Happy coding!👏👏👏
>
> Feel free to leave any questions or comments in the PR thread if something
> is not 100% clear.
> Please, remember to tag me in your question so I can receive the
> notification.
> ------------------------------
>
> *As described in the Code reviews limits policy
> <https://microverse.zendesk.com/hc/en-us/articles/1500004088561> you have a
> limited number of reviews per project (check the exact number in your
> Dashboard). If you think that the code review was not fair, you can request
> a second opinion using this form <https://airtable.com/shrQAqnBwek5a0O0s>.*
> ------------------------------
>
> In README.md
> <https://github.com/seyioyemade/hello-world/pull/1#discussion_r1107180441>
> :
>
> > +### Install
>
> +
>
> +Install this project with:
>
> +
>
> +-Copy the URL [https://github.com/seyioyemade/hello-world.git].
>
> +
>
> +-In Visual Studio Code “Terminal” change the current working directory to the location where you want the cloned directory.
>
> +
>
> +-Type git clone in the terminal, paste the URL you copied earlier, and press “enter” to create your local clone.
>
> +
>
> +git clone [https://github.com/seyioyemade/hello-world.git]
>
> +
>
>
> [ OPTIONAL ]
> well done @seyioyemade <https://github.com/seyioyemade>, you implemented
> all this project requirements and applied all changes required by previous
> reviewers 💪, one small thing to mention is that the content of this
> section should move to setup and here all user have to do is run ' npm
> install '.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/seyioyemade/hello-world/pull/1#pullrequestreview-1299578718>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/A3IEW72BIIFJ33GIB2A5JZLWXTQQ7ANCNFSM6AAAAAAU4A5FQY>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2023-02-15 14:25 UTC, merged